services:
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/walletdb
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  db:
    image: postgres:16.1
    container_name: db-container
    ports:
      - "6532:5432"
    environment:
      - POSTGRES_DB=walletdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
